### ISSUE TITLE
I am completely confused. How doest it works?

### ISSUE THREAD

**Issue by muhajirframe** [superawesomelabs/leo#184]
Hi, I thinks it's very great and modern static site generator. I see it use latest tech such as graphql.

But I completely confused, how is differ from a common static site generator, or even another tools such nuxtjs which could generate static website too from a vuejs project.

**Comment by ChristopherBiscardi** [comment]
If you are confused by this project you probably don't need it and would be happier using [gatsby](https://github.com/gatsbyjs/gatsby) or nuxt as you said.

There is a [video](https://www.youtube.com/watch?v=k_D2ZT2Pu1c) where I explain more about why this project exists.
